config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'store#index', as: :store

  resources :shops
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :products_shops, dependent: :destroy
  has_many :shops, through: :products_shops

  validates :name, presence: true
end

app/models/products_shop.rb
class ProductsShop < ApplicationRecord
  belongs_to :shop
  belongs_to :product

  validates :product_id, uniqueness: { scope: [:product_id, :shop_id] }
  validates :price, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  geocoded_by :full_address

  has_many :products_shops, dependent: :destroy
  has_many :products, through: :products_shops

  accepts_nested_attributes_for :products_shops, reject_if: :all_blank, allow_destroy: true

  validates :city, :street, :zip, presence: true

  after_validation :geocode, if: :address_attributes_changed?

  scope :default, -> { where(default_for_all: true).first }

  def full_address
    [city, street, zip].compact.join(', ')
  end

  def address_attributes_changed?
    return true if new_record?
    %w[city street zip].each do |attr|
      return true if send(attr).present? && send("#{attr}_changed?")
    end
    return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show; end
  def edit; end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: t('activerecord.notices.cteated')
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: t('activerecord.notices.updated')
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path, notice: t('activerecord.notices.deleted')
    end
  end

  private

  def product_params
    params.require(:product).permit(:id, :name)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  helper_method :products_for_select

  before_action :set_shop, only: %i[edit update show destroy]

  def new
    @shop = Shop.new
  end

  def show; end

  def index
    @shops = Shop.all
  end

  def create
    @shop = Shop.new(shop_params)

    if @shop.save
      redirect_to shops_path, notice: t('activerecord.notices.cteated')
    else
      render :new
    end
  end

  def update
    if @shop.update(shop_params)
      redirect_to @shop, notice: t('activerecord.notices.updated')
    else
      render :edit
    end
  end

  def destroy
    if @shop.destroy
      redirect_to shops_path, notice: t('activerecord.notices.deleted')
    end
  end

  private

  def shop_params
    params.require(:shop).permit(
      :id, :city, :street, :zip, :latitude, :longitude, :default_for_all,
      products_shops_attributes: [:id, :product_id, :price, :_destroy]
    )
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def products_for_select
    Product.all.map { |p| [p.name, p.id] }
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  DISTANCE = 500.freeze

  before_action :set_shop
  before_action :set_shops, only: :index

  def index
    respond_to do |format|
      format.js   { render 'index.js.erb' }
      format.html {}
    end
  end

  private

  def set_shop
    @shop =
      if position = params[:position]
        Shop.near([position[:latitude], position[:longitude]], DISTANCE).first
      elsif params[:selected_shop]
        shop = Shop.find(params[:selected_shop][:shop_id])
        update_cookies(shop) && shop if shop
      else
        lat  = cookies['latitude']
        long = cookies['longitude']

        Shop.near([lat, long], DISTANCE).first || Shop.default
      end
  end

  def set_shops
    @shops = Shop.all.map { |shop| [shop.full_address, shop.id] }
  end

  def update_cookies(shop)
    cookies['latitude']  = shop.latitude
    cookies['longitude'] = shop.longitude
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page_name
    I18n.t("#{controller_name}.#{action_name}.page_name")
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
  def edit_or_update_action?
    action_name == 'edit' || action_name == 'update'
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title nearest_atm
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag :cocoon
    = csrf_meta_tags

    link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css" rel="stylesheet"

  header
    =render 'shared/nav_bar'
  body
    .container
      = render template: 'shared/notices'

      h3 = current_page_name
      = yield

app/views/products/_form.html.slim
= render partial: 'shared/errors_messages', locals: { resource: @product }

= form_for @product, html: { class: 'form form-inline' } do |f|
  .form-group
    = f.label :name
    |&nbsp
    = f.text_field :name, class: 'form-control'
    |&nbsp
  = f.submit t('buttons.save'), class: 'display-none', id: 'submit_product'

app/views/products/edit.html.slim
= render 'form'
br
.row
  .col-md-6
    = link_to t('buttons.back'), product_path(@product), class: 'btn btn-primary'
    | &nbsp
    = label_tag :submit_product, t('buttons.save'), class: 'btn btn-success'

app/views/products/index.html.slim
.result-table
  table.table.table-condensed.text-center
    thead
      tr
        th.text-center #
        th.text-center id
        th.text-center = t('activerecord.attributes.product.name')
        th.text-center = t('buttons.actions')
    tbody
      - @products.each.with_index(1) do |product, index|
        tr id="#{product.id}"
          td = index
          td = product.id
          td = product.name
          td
            = link_to t('buttons.show'),    product_path(product)
            = ' | '
            = link_to t('buttons.edit'),    edit_product_path(product)
            = ' | '
            = link_to t('buttons.destroy'), product_path(product), method: :delete,
                    data: { confirm: 'Are you sure?' }
= link_to t('buttons.new'), new_product_path, class: 'btn btn-default'

app/views/products/new.html.slim
.text-center
  = render 'form'
.row
  .col-md-6
    = link_to t('buttons.back'), products_path, class: 'btn btn-primary'
    | &nbsp
    = label_tag :submit_product, t('buttons.save'), class: 'btn btn-success'

app/views/products/show.html.slim
p
  = Product.human_attribute_name(:name)
  = ': '
  = @product.name
br
.row
  = link_to t('buttons.back'), products_path, class: 'btn btn-primary'
  | &nbsp
  = link_to t('buttons.edit'), edit_product_path(@product), class: 'btn btn-default'

app/views/shared/_errors_messages.html.slim
- if resource.errors.any?
  .alert.alert-danger.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times;
    p = t('activerecord.errors.header_title')
    - resource.errors.messages.each do |attribute, messages|
      - messages.each do |message|
        = "#{attribute} #{message}"
        br

app/views/shared/_nav_bar.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#{store_path}"  = t('brand')
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to t('all_shops'), shops_path
        li
          = link_to t('all_products'), products_path

app/views/shared/notices.html.slim
-flash.each do |type, message|
  .alert.alert-success.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times;
    .text-center
      = message

app/views/shops/_form.html.slim
= render partial: 'shared/errors_messages', locals: {resource: @shop}

= form_for @shop, html: {class: 'form form-inline'} do |f|
  .form-group
    = f.label :city
    |&nbsp
    = f.text_field :city, class: 'form-control'
    |&nbsp
  .form-group
    = f.label :street
    |&nbsp
    = f.text_field :street, class: 'form-control'
    |&nbsp
  .form-group
    = f.label :zip
    |&nbsp
    = f.text_field :zip, class: 'form-control'
    |&nbsp
  #products_shops
    - if edit_or_update_action?
      br
      p.text-left
        = link_to_add_association t('buttons.add_product'), f, :products_shops,
            { \
              :'data-association-insertion-traversal' => :closest,\
              :'data-association-insertion-node' => '#products_shops',\
              :'data-association-insertion-method' => :append,\
              class: 'btn btn-default'\
            }
      = f.fields_for :products_shops do |ps|
        = render partial: 'products_shop_fields', locals: { f: ps }
  br
  = f.submit t('buttons.save'), class: 'display-none', id: 'submit_shop'

app/views/shops/_products_shop_fields.html.slim
.nested-fields.row
  .form-group
    = f.label :product_id
    |&nbsp
    = f.select :product_id, options_for_select(products_for_select, f.object.product_id), {},
            { class: 'js-product-select' }
  .form-group
    = f.label :price
    |&nbsp
    = f.text_field :price, class: 'form-control'
  .form-group
    | &nbsp
    = link_to_remove_association t('buttons.destroy'), f

app/views/shops/edit.html.slim
= render 'form'
.row
  .col-md-6
    = link_to t('buttons.back'), shop_path(@shop), class: 'btn btn-primary'
    | &nbsp
    = label_tag :submit_shop, t('buttons.save'), class: 'btn btn-success'
  .col-md-6.text-right
    = link_to t('buttons.destroy'), shop_path(@shop), method: :delete, data: { confirm: t('buttons.confirm') },
            class: 'btn btn-danger'

app/views/shops/index.html.slim
.result-table
  table.table.table-condensed.text-center
    thead
      tr
        th.text-center #
        th.text-center id
        th.text-center = t('activerecord.attributes.shop.address')
        th.text-center = t('buttons.actions')
    tbody
      - @shops.each.with_index(1) do |shop, index|
        tr id="#{shop.id}"
          td = index
          td = shop.id
          td = shop.full_address
          td
            = link_to t('buttons.show'),    shop_path(shop)
            = ' | '
            = link_to t('buttons.edit'),    edit_shop_path(shop)
            = ' | '
            = link_to t('buttons.destroy'), shop_path(shop), method: :delete,
                    data: { confirm: t('buttons.confirm')}
= link_to t('buttons.new'), new_shop_path, class: 'btn btn-default'

app/views/shops/new.html.slim
= render 'form'
.row
  .col-md-6
    = link_to t('buttons.back'), shops_path, class: 'btn btn-primary'
    | &nbsp
    = label_tag :submit_shop, t('buttons.save'), class: 'btn btn-success'

app/views/shops/show.html.slim
= @shop.full_address

- if @shop.products.present?
  h4.text-center = t('activerecord.attributes.product.product_header')

  .result-table
    table.table.table-condensed.text-center
      thead
        tr
          th.text-center #
          th.text-center = t('activerecord.attributes.product.name')
          th.text-center = t('activerecord.attributes.products_shop.price')
      tbody
        - @shop.products_shops.each.with_index(1) do |record, index|
          tr id="#{record.product.id}"
            td = index
            td = record.product.name
            td = record.price
- else
  h4.text-center = t('search_result.no_records')

- unless controller_name == 'store'
  .row
    = link_to t('buttons.back'), shops_path, class: 'btn btn-primary'
    | &nbsp
    = link_to t('buttons.edit'), edit_shop_path(@shop), class: 'btn btn-default'

app/views/store/_store.html.slim
p
  = label_tag 'shops', t('activerecord.attributes.store.shops')
  = select_tag 'shops', options_for_select(@shops, cookies['selected_shop'] || @shop.id),
          class: 'js-shops-select'
= render template: 'shops/show'

app/views/store/index.html.slim
.js-store
  p = render partial: 'store', locals: { shop: @shop }

app/views/store/index.js.erb
$('.js-store').html("<%= j render partial: 'store', locals: { shop: @shop } %>")